---
sudo: required
dist: trusty
language: python
python: "2.7"

env:
  - SITE=test.yml
  - SITE=test-phpunit.yml

before_install:
  - sudo apt-get update -qq

install:
  ## Install Ansible.
  ## TODO: REMOVE <2 once ansible 2.0 becomes more stable
  - pip install 'ansible<2'

  # Add ansible.cfg to pick up roles path.
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

  # Download dependencies
  - ansible-galaxy install telusdigital.apt-repository telusdigital.logrotate telusdigital.upstart

script:
  # Check the role/playbook's syntax.
  - "ansible-playbook -i tests/inventory tests/$SITE --syntax-check"

  # Run the role/playbook with ansible-playbook.
  - "ansible-playbook -i tests/inventory tests/$SITE --connection=local --sudo"

  # Run the role/playbook in --check mode.
  - "ansible-playbook -i tests/inventory tests/$SITE --connection=local --sudo --check"

  # Make sure PHP is available.
  - >
    php -v
    | grep -q 'The PHP Group'
    && (echo 'PHP is installed' && exit 0)
    || (echo 'PHP is not installed' && exit 1)

  # And for posterity...
  - php -v

notifications:
  slack:
    secure: cEZ0Vuesx5bALOcVaE3NGLeg4va40gJSgh1Fd81w+SNzh+UuznGEUMEY9esPULm2naXFHyQaqHCejHLTmHv8LfO+V1R4t2YiAtm3y5siy5CY2txxL6ycxbu0cdUrSZTlgumTbDfo5byJBRD8/r8mILBxX4IIA9YkCIj58o2U4YAIPYo/UmZK4Gx3DUwAktXpAVmc93FOKsXPNT1g+Kbl/lwdhnj4+llZoIoHWmDQ7+FNz1J1RTadvo384GJD68XyITDYdaKZIqvAcIJGrJXJHj9/PfAiEgOjphaFdM0hBYL6jtGwMv50Nfy2J6F+fB2DjmXASzPILTN3CC+zBF5ef+7TlgFVaij0ktL9OCC3qmmlL7FjQYIXdbHzUvs+wkAWBysLjOfoJv2TVPXQpC1tnJym/eOd6ieNFvaQeZewDUWfY1yffNG4hxOfgvfHceLGDbzf69hcJTVkHDhkGHUyZ4hEVVS3xqtuLjCZZXhN2Q5TGBdkyMHZ3K3KoHkrWBKR22z7PkdxvWMRl8E4A9C9rFxwYpF87XCqfDjTH+VRsSOsyiXK9tQFdfE3pYqSSiJgN1gK9TCxD7/yDDflL8zzDIZR95Ursf7ZyWRz4IBUbPGs5T/cAzcEN1uLScvSNKugNeSNgA8bIP4Vw3colJLGfrV2Ze6SGxa3TgSPiSRLz4Y=

