---
- name: service | php-fpm | started
  service:
    name: "{{ php_fpm_service_name }}"
    state: started

- name: service | php-fpm | stopped
  service:
    name: "{{ php_fpm_service_name }}"
    state: stopped

- name: service | php-fpm | restarted
  service:
    name: "{{ php_fpm_service_name }}"
    state: restarted

- name: service | php-fpm | reloaded
  service:
    name: "{{ php_fpm_service_name }}"
    state: reloaded
